# http://www.appveyor.com/docs/appveyor-yml

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "0.12"

install:
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - cmd: npm config set spin false
  - cmd: npm install -g npm@^2
  - cmd: npm install -g ember-cli bower
  - cmd: npm install
  - cmd: bower install
  - cmd: npm run-script release
  - ps: Copy-Item .\*.txt .\dist

# Don't actually build.
build: off

# Tests are executed elsewhere
test: off

# Set build version format here instead of in the admin panel.
version: "{build}"

artifacts:
  - path: .\dist
    name: Klondike
    type: zip
  - path: LICENSE.txt
    name: License
  - path: COPYRIGHT.txt
    name: Copyright
